py_library(
    name = "runners",
    srcs = ["base_runner.py",
            "tfa_runner.py",
            "ppo_runner.py",
            "dqn_runner.py",
            "cdqn_runner.py",
            "sac_runner.py"],
    visibility = ["//visibility:public"],
)